version: '3'

services:
  db:
    image: "postgres:11"
    init: true
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    init: true
    restart: on-failure
    command: ["./wait-for-it.sh", "db:5432", "--", "make", "runserver"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

# https://myshittycode.com/2017/06/01/docker-defining-custom-location-for-named-volume/
volumes:
  postgres_data:
    driver_opts:
      type: none
      device: /data/postgres_data
      o: bind
