version: '3'

services:
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_HOST="${POSTGRES_HOST}"
      # - POSTGRES_PORT="${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "make", "runserver"]
    # environment:
      # - DEBUG="${DEBUG}"
      # - SECRET_KEY="${SECRET_KEY}"
      # - DATABASE_URL="${DATABASE_URL}"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
