version: '3'

services:
  db:
    image: postgres:latest
    init: true
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

  web:
    build: .
    init: true
    restart: on-failure
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "make", "gunicorn"]
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

  celery:
    build: .
    command: celery worker -A dj_play --workdir /app/dj_play -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery beat -A dj_play --workdir /app/dj_play -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
# https://myshittycode.com/2017/06/01/docker-defining-custom-location-for-named-volume/
volumes:
  postgres_data:
    driver_opts:
      type: none
      device: /data/postgres_data
      o: bind

