# Generated by Django 3.1.2 on 2020-10-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtue",
            name="next_level_xp",
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="virtue",
            name="level_up_xp_modifier",
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name="virtue",
            name="xp_to_next_level",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="virtue",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
