# Generated by Django 3.1.2 on 2020-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201028_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtue',
            name='xp_to_next_level_constant',
            field=models.FloatField(default=3.0),
        ),
    ]
